# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-11-24 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0013_remove_file_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='filefolder',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Public'),
        ),
    ]
