# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-10-28 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0023_auto_20171112_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='phone',
            field=models.CharField(default='', max_length=50, verbose_name='Numéro de téléphone'),
        ),
    ]
