# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-11-03 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0024_auto_20181028_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='latex_color_name',
            field=models.CharField(default='', help_text='Used for LaTeX generation, see the .sty for more info', max_length=100),
            preserve_default=False,
        ),
    ]
