# Generated by Django 2.2.4 on 2019-10-05 11:28

from django.conf import settings
from django.db import migrations, models
import portailva.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('association', '0026_auto_20190817_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='all_members_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de membres adhérents'),
        ),
        migrations.AddField(
            model_name='association',
            name='commentary',
            field=models.TextField(blank=True, help_text="Cette description n'est pas visible pour les non-administateurs", verbose_name='Commentaires'),
        ),
        migrations.AddField(
            model_name='association',
            name='created_officially_at',
            field=models.DateField(blank=True, help_text='Format : JJ/MM/AAAA', null=True, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='association',
            name='moderated_by',
            field=models.ManyToManyField(blank=True, related_name='referent', to=settings.AUTH_USER_MODEL, verbose_name='Référent CVA'),
        ),
        migrations.AddField(
            model_name='association',
            name='rna',
            field=models.CharField(blank=True, max_length=10, verbose_name='Numéro RNA'),
        ),
        migrations.AddField(
            model_name='association',
            name='siren',
            field=models.CharField(blank=True, max_length=9, validators=[portailva.utils.validators.validate_siren], verbose_name='Numéro SIREN'),
        ),
        migrations.AddField(
            model_name='mandate',
            name='share_phone',
            field=models.BooleanField(default=False, verbose_name='Autoriser le partage du numéro'),
        ),
    ]
