# Generated by Django 2.2.4 on 2019-10-09 14:47

from django.db import migrations, models
import portailva.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0027_auto_20191005_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='siren',
            field=models.CharField(blank=True, help_text='Format : XXXXXXXXX où X est un chiffre entre 0 et 9', max_length=9, validators=[portailva.utils.validators.validate_siren], verbose_name='Numéro SIREN'),
        ),
    ]
