# Generated by Django 2.2.4 on 2019-11-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0028_auto_20191009_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='acronym',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nom usuel ou acronyme'),
        ),
        migrations.AlterField(
            model_name='association',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nom officiel'),
        ),
        migrations.AlterField(
            model_name='association',
            name='rna',
            field=models.CharField(blank=True, help_text="La date extacte ainsi que les numéros d'identifications ci-dessous peuvent être facilement retrouvés en cherchant votre asso sur le site : entreprise.data.gouv.fr", max_length=10, verbose_name='Numéro RNA'),
        ),
    ]
