# Generated by Django 2.2.8 on 2020-03-23 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0030_association_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomplishment',
            name='requirement',
            field=models.ForeignKey(limit_choices_to={'type': ['accomplishment', 'room']}, on_delete=django.db.models.deletion.CASCADE, to='association.Requirement', verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='type',
            field=models.CharField(choices=[('mandate', 'Mandat'), ('file', 'Fichier'), ('accomplishment', 'Validation manuelle'), ('room', 'Validation manuelle (nécessite un local)')], max_length=40, verbose_name='Type de condition'),
        ),
    ]
