# Generated by Django 2.2.4 on 2019-08-22 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_auto_20190817_1331'),
        ('directory', '0005_auto_20190820_2232'),
    ]

    operations = [
    ]
