# Generated by Django 2.2.4 on 2019-11-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_merge_20190822_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='directoryentry',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL fil Instagram'),
        ),
    ]
