# Generated by Django 2.2.4 on 2019-11-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20171112_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='color',
            field=models.CharField(default='#007bff', max_length=7, verbose_name='Couleur'),
        ),
    ]
