# Generated by Django 2.2.8 on 2020-04-09 15:31

from django.db import migrations, models
import portailva.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_event_facebook_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='begin_publication_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Début d'affichage"),
        ),
        migrations.AddField(
            model_name='event',
            name='content_url',
            field=portailva.utils.fields.AffichageURLField(blank=True, help_text="Privilégiez les liens en HTTPS. Assurez-vous que le lien que vous fournissez pointe directement sur la ressource (pas de page d'affichage comme Google Drive ou autres) et que la ressource soit accessible. Vous pouvez mettre en ligne une image (en .png, .jpg, ou .jpeg, et idéalement au format 1920x1080px), un pdf, une vidéo Youtube ou une page web de votre choix.", null=True, verbose_name='Url du contenu'),
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.IntegerField(blank=True, default=7, verbose_name="Durée d'apparition à l'écran (en s)"),
        ),
        migrations.AddField(
            model_name='event',
            name='end_publication_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Fin d'affichage"),
        ),
        migrations.AddField(
            model_name='event',
            name='has_poster',
            field=models.BooleanField(default=False, verbose_name='Est à publier sur Affichage ?'),
        ),
    ]
