# Generated by Django 2.2.8 on 2020-03-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_auto_20171010_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_room',
            field=models.BooleanField(default=False, verbose_name='Est un local'),
        ),
    ]
